# Generated by Django 5.0.4 on 2024-05-01 22:02
import pandas as pd

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    def insert_init_data(apps, schema_editor):
        df = pd.read_csv('Cotizador/migrations/Servicios y categorías.csv')

        list_categorias = df['CATEGORIA'].unique()

        Categoria = apps.get_model('Cotizador', 'Categoria')

        for i in list_categorias:
            Categoria.objects.create(descripcion = i)


    def undo_insert_data(apps, schema_editor):
        Categoria = apps.get_model('Cotizador', 'Categoria')
        Categoria.objects.all().delete()

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30, unique=True, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
                'ordering': ['id'],
            },
        ),
        

        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30, unique=True, verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehiculos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
                ('idCategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cotizador.categoria', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'servicios',
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(insert_init_data, reverse_code =  undo_insert_data)
    ]

    
