# Generated by Django 5.0.4 on 2024-05-01 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cotizador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.CharField(max_length=30, unique=True, verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='idCategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cotizador.categoria'),
        ),
    ]
