# Generated by Django 5.0.4 on 2024-09-10 17:57

import django.db.models.deletion
from django.db import migrations, models
import pandas as pd


class Migration(migrations.Migration):

    dependencies = [
        ('Cotizador', '0001_initial'),
        ('Proveedores', '0001_initial'),
    ]

    def insert_init_data(apps, schema_editor):

        Tarifa = apps.get_model('Cotizador', 'Tarifa')
        VehiculoServicio = apps.get_model('Cotizador', 'VehiculoServicio')
        VehiculoServicio_objetos = VehiculoServicio.objects.all()
        Proveedor = apps.get_model('Proveedores', 'Proveedor')
        proveedorbd1 = Proveedor.objects.get(empresa= 'TUPAC PRITIVÍ LEÓN')
        proveedorbd2 = Proveedor.objects.get(empresa= 'PANDÚ NÁMASTE RIVAS')
       

        list_servicios_register_objs = []

        for item in VehiculoServicio_objetos:
            list_servicios_register_objs.append(
                Tarifa(
                    idVechiculoServicio = item ,
                    idProveedor  = proveedorbd1,
                    precio_unitario = '10550'
                ))
            list_servicios_register_objs.append(
                Tarifa(
                    idVechiculoServicio = item ,
                    idProveedor  = proveedorbd2,
                    precio_unitario = '15000'
                )
            )
        
        Tarifa.objects.bulk_create (list_servicios_register_objs)  
        
    def undo_insert_data(apps, schema_editor):
        Tarifa = apps.get_model('Cotizador', 'Tarifa')
        Tarifa.objects.all().delete()

    operations = [
        migrations.CreateModel(
            name='Cotizacion_cabecera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cotizador.cliente')),
            ],
            options={
                'verbose_name': 'Cotización cabecera',
                'verbose_name_plural': 'Cotizaciones cabecera',
                'db_table': 'cotizaciones_cab',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cotizacion_linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio x Unidad')),
                ('contacto', models.BooleanField(default=False, verbose_name='Contacto')),
                ('idCoticazion_cab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cotizador.cotizacion_cabecera', verbose_name='Cotización cabecera')),
                ('idProveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proveedores.proveedor', verbose_name='Proveedor')),
                ('idVechiculoServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cotizador.vehiculoservicio', verbose_name='Vehículo-Servicio')),
            ],
            options={
                'verbose_name': 'Cotización linea',
                'verbose_name_plural': 'Cotizaciones linea',
                'db_table': 'cotizaciones_linea',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio x Unidad')),
                ('idProveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proveedores.proveedor', verbose_name='Proveedor')),
                ('idVechiculoServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cotizador.vehiculoservicio', verbose_name='Vehículo-Servicio')),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
                'db_table': 'tarifa',
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(insert_init_data, reverse_code =  undo_insert_data)
    ]
