# Generated by Django 5.0.4 on 2024-09-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cotizador', '0002_cotizacion_cabecera_cotizacion_linea_tarifa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('P', 'Particular'), ('E', 'Empresa')], default='P', max_length=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
    ]
