# Generated by Django 5.0.4 on 2024-05-01 23:07
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cotizador', '0002_alter_servicio_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.CharField(max_length=60, unique=True, verbose_name='Servicio'),
        ),
        #
    ]
