# Generated by Django 5.0.4 on 2024-11-14 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cotizador', '0003_cliente_tipo_alter_cliente_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion_cabecera',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.RemoveField(
            model_name='cotizacion_linea',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='cotizacion_linea',
            name='idVechiculoServicio',
        ),
        migrations.AddField(
            model_name='cotizacion_cabecera',
            name='cantidad',
            field=models.IntegerField(default=2, verbose_name='Cantidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotizacion_cabecera',
            name='idVehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cotizador.vehiculo', verbose_name='Vehículo'),
        ),
        migrations.AddField(
            model_name='cotizacion_linea',
            name='idCategoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Cotizador.categoria', verbose_name='Categoría'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotizacion_linea',
            name='idServicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cotizador.servicio', verbose_name='Servicio'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
