# Generated by Django 5.0.4 on 2024-05-02 03:37
import pandas as pd
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cotizador', '0003_alter_servicio_descripcion'),
    ]
    def insert_init_data(apps, schema_editor):
        df = pd.read_csv('Cotizador/migrations/Servicios y categorías.csv')
        
        #list_categorias = df['CATEGORIA'].unique()
        
        Categoria = apps.get_model('Cotizador', 'Categoria')
        Servicio = apps.get_model('Cotizador', 'Servicio')
        

        list_servicios_register_objs = []
        for i, row in df.iterrows():

            categoriabd = Categoria.objects.get(descripcion = row['CATEGORIA'])

            #No funciona
            
            list_servicios_register_objs.append(
                Servicio(
                    idCategoria = categoriabd,
                    descripcion = row['SERVICIO']
                )
            )    
        print(list_servicios_register_objs)
        Servicio.objects.bulk_create (list_servicios_register_objs)  

    def undo_insert_data(apps, schema_editor):
        Servicio = apps.get_model('Cotizador', 'Servicio')
        Servicio.objects.all().delete()

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.CharField(max_length=60, verbose_name='Servicio'),
        ),
        migrations.RunPython(insert_init_data, reverse_code =  undo_insert_data)
    ]
