# Generated by Django 5.0.4 on 2024-11-14 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cotizador', '0004_alter_cotizacion_cabecera_idcliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizacion_linea',
            old_name='idCoticazion_cab',
            new_name='idCotizazion_cab',
        ),
    ]
